### ISSUE TITLE
基于 baichuan-inc/Baichuan-7B 进行 pretrain 报错

### ISSUE THREAD

**Issue by Remember2015** [shibing624/MedicalGPT#106]
使用 baichuan-7b 模型进行增量预训练报错，数据集直接使用的仓库中自带的，未做调整
- 环境
  - nvidia 4090 * 2
  - 库版本
    - peft==0.4.0
    - transformers==4.31.0
    - torch==2.0.1
    - accelerate==0.21.0
    - bitsandbytes==0.40.2
- run_pt.sh
```js
CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node 2 pretraining.py \
    --model_type baichuan \
    --model_name_or_path baichuan-inc/Baichuan-7B \
    --train_file_dir ./data/pretrain \
    --validation_file_dir ./data/pretrain \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --do_train \
    --do_eval \
    --use_peft True \
    --seed 42 \
    --fp16 \
    --max_train_samples 10000 \
    --max_eval_samples 10 \
    --num_train_epochs 0.5 \
    --learning_rate 2e-4 \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 1 \
    --block_size 1024 \
    --output_dir outputs-baichuan-pt \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --load_in_8bit True \
    --gradient_checkpointing True
```
- error
```
Traceback (most recent call last):
  File "/home/luke/medicalgpt/pretraining.py", line 660, in <module>
    main()
  File "/home/luke/medicalgpt/pretraining.py", line 632, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/luke/medicalgpt/.venv/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/luke/medicalgpt/.venv/lib/python3.10/site-packages/transformers/trainer.py", line 1888, in _inner_training_loop
    self.optimizer.step()
  File "/home/luke/medicalgpt/.venv/lib/python3.10/site-packages/accelerate/optimizer.py", line 133, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/luke/medicalgpt/.venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 372, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
Traceback (most recent call last):
  File "/home/luke/medicalgpt/pretraining.py", line 660, in <module>
    main()
  File "/home/luke/medicalgpt/pretraining.py", line 632, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/luke/medicalgpt/.venv/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/luke/medicalgpt/.venv/lib/python3.10/site-packages/transformers/trainer.py", line 1888, in _inner_training_loop
    self.optimizer.step()
  File "/home/luke/medicalgpt/.venv/lib/python3.10/site-packages/accelerate/optimizer.py", line 133, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/luke/medicalgpt/.venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 372, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
  0%|                                                                                                                        | 0/31 [00:02<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 946743) of binary: /home/luke/medicalgpt/.venv/bin/python
```

**Comment by Remember2015** [comment]
补充一下，用 `bigscience/bloomz-560m` 可以 pt 完

**Comment by shibing624** [comment]
我测试了下，baichuan-7b微调训练，需要的显存比llama-7b大一倍，我用下面命令执行成功的。

```
CUDA_VISIBLE_DEVICES=0,1 python pretraining.py ...
```
