### ISSUE TITLE
微调chatglm报错assert self.padding_side == "left"

### ISSUE THREAD

**Issue by wusi1590** [shibing624/MedicalGPT#111]
做chatglm模型微调的tokenizee过程中报错
我只是把参数中的model_type和template_name改了，数据就用的自带的数据
    --model_type chatglm \
    --train_file_dir ./data/finetune \
    --template_name chatglm \
请问微调chatglm的时候是应该改这两个参数么，还是说数据文件的格式也要改呢，如果要改，改成什么样子的？

Running tokenizer on dataset:   0%|                                                                                                                         | 0/1000 [00:03<?, ? examples/s]
Traceback (most recent call last):
  File "/home/zengli/wusijie/MedicalGPT/supervised_finetuning.py", line 912, in <module>
    main()
  File "/home/zengli/wusijie/MedicalGPT/supervised_finetuning.py", line 818, in main
    train_dataset = train_dataset.shuffle().map(
  File "/home/zengli/.conda/envs/w3.9/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/zengli/.conda/envs/w3.9/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/zengli/.conda/envs/w3.9/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3097, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/zengli/.conda/envs/w3.9/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3474, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/home/zengli/.conda/envs/w3.9/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/home/zengli/wusijie/MedicalGPT/supervised_finetuning.py", line 760, in preprocess_function
    input_ids = tokenizer(
  File "/home/zengli/.conda/envs/w3.9/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2577, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/zengli/.conda/envs/w3.9/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2663, in _call_one
    return self.batch_encode_plus(
  File "/home/zengli/.conda/envs/w3.9/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2854, in batch_encode_plus
    return self._batch_encode_plus(
  File "/home/zengli/.conda/envs/w3.9/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 737, in _batch_encode_plus
    batch_outputs = self._batch_prepare_for_model(
  File "/home/zengli/.conda/envs/w3.9/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 809, in _batch_prepare_for_model
    batch_outputs = self.pad(
  File "/home/zengli/.conda/envs/w3.9/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3061, in pad
    outputs = self._pad(
  File "/home/zengli/.cache/huggingface/modules/transformers_modules/chatglm-6b/tokenization_chatglm.py", line 384, in _pad
    assert self.padding_side == "left"
AssertionError

然后我又试了chatglm2模型微调，会报另一个错：
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:26<00:00,  3.73s/it]
Traceback (most recent call last):
  File "/home/zengli/wusijie/MedicalGPT/supervised_finetuning.py", line 912, in <module>
    main()
  File "/home/zengli/wusijie/MedicalGPT/supervised_finetuning.py", line 646, in main
    tokenizer.pad_token = tokenizer.unk_token
AttributeError: can't set attribute

**Comment by shibing624** [comment]
我适配下chatglm2

**Comment by wusi1590** [comment]
> 我适配下chatglm2

assert self.padding_side == "left"
AssertionError
请问chatglm1的这个问题该怎么解决？

**Comment by shibing624** [comment]
手动设置padding_side = left。

**Comment by icesun963** [comment]
借楼问以下。chatglm2 sf微调 padding_side = left 直接使用你的自带 数据，输出一堆空格。
