### ISSUE TITLE
rl_training.py  ValueError: The model does not have a language model head, please use a model that has one.

### ISSUE THREAD

**Issue by qingjiaozyn** [shibing624/MedicalGPT#126]
Traceback (most recent call last):
  File "rl_training.py", line 466, in <module>
    main()
  File "rl_training.py", line 254, in main
    model = AutoModelForCausalLMWithValueHead.from_pretrained(
  File "/home/zyn/deepchat/deepspeed/lib/python3.8/site-packages/trl/models/modeling_base.py", line 232, in from_pretrained
    model = cls(pretrained_model, **trl_model_args)
  File "/home/zyn/deepchat/deepspeed/lib/python3.8/site-packages/trl/models/modeling_value_head.py", line 107, in __init__
    raise ValueError("The model does not have a language model head, please use a model that has one.")
ValueError: The model does not have a language model head, please use a model that has one.
训练第四步显示没有模型头

**Comment by shibing624** [comment]
PPO训练依赖于trl库，AutoModelForCausalLMWithValueHead不兼容的模型，暂时无法处理。
