### ISSUE TITLE
AttributeError: 'BaiChuanConfig' object has no attribute 'num_key_value_heads'

### ISSUE THREAD

**Issue by qingjiaozyn** [shibing624/MedicalGPT#127]
Traceback (most recent call last):
  File "reward_modeling.py", line 649, in <module>
    main()
  File "reward_modeling.py", line 397, in main
    model = model_class.from_pretrained(
  File "/home/zyn/deepchat/deepspeed/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/zyn/deepchat/deepspeed/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 911, in __init__
    self.model = LlamaModel(config)
  File "/home/zyn/deepchat/deepspeed/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 561, in __init__
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "/home/zyn/deepchat/deepspeed/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 561, in <listcomp>
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "/home/zyn/deepchat/deepspeed/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 375, in __init__
    self.self_attn = LlamaAttention(config=config)
  File "/home/zyn/deepchat/deepspeed/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 242, in __init__
    self.num_key_value_heads = config.num_key_value_heads
  File "/home/zyn/deepchat/deepspeed/lib/python3.8/site-packages/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)
使用baichuan模型运行到第三步出现的这个问题，跟踪原因是baichuan模型使用的LlamaForSequenceClassification
![image](https://github.com/shibing624/MedicalGPT/assets/140772087/b7ca4144-9884-435b-ac75-76b45c6f52b3)
baichuan是否可使用LlamaForSequenceClassification，这两个是否兼容
目前使用的transformers版本为 4.31.0，是否需要更改transformers版本，更改为哪个版本

**Comment by shibing624** [comment]
baichuan 跟chatglm一样，代码没有push到transformers，没有SequenceClassification类的方法，暂不支持reward
