### ISSUE TITLE
增量预训练报错：AssertionError: No inf checks were recorded for this optimizer.

### ISSUE THREAD

**Issue by QJBX-DJN** [shibing624/MedicalGPT#138]
### Describe the Question
Please provide a clear and concise description of what the question is.
使用 baichuan-13b-Chat 模型进行增量预训练报错，数据集直接使用的仓库中自带的，未做调整
改为仓库中自带的bloom案例依然报错
环境为2*3090

- baichuan-13b-Chat run_pt.sh
```
CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node 2 pretraining.py \
    --model_type baichuan \
    --model_name_or_path /workspace/llm/Baichuan-13B-Chat \
    --train_file_dir ./data/pretrain \
    --validation_file_dir ./data/pretrain \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 4 \
    --do_train \
    --do_eval \
    --use_peft True \
    --seed 42 \
    --fp16 \
    --max_train_samples 10000 \
    --max_eval_samples 10 \
    --num_train_epochs 0.5 \
    --learning_rate 2e-4 \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 1 \
    --block_size 1024 \
    --output_dir outputs-pt-v1 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --load_in_8bit True \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True
```

-bloom run_pt.sh

```
CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node 2 pretraining.py \
    --model_type bloom \
    --model_name_or_path /workspace/llm/bloom \
    --train_file_dir ./data/pretrain \
    --validation_file_dir ./data/pretrain \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --do_train \
    --do_eval \
    --use_peft True \
    --seed 42 \
    --fp16 \
    --max_train_samples 10000 \
    --max_eval_samples 10 \
    --num_train_epochs 0.5 \
    --learning_rate 2e-4 \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 1 \
    --block_size 1024 \
    --output_dir outputs-pt-v1 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --load_in_8bit True \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True
```

- error
```
Traceback (most recent call last):
  File "pretraining.py", line 663, in <module>
    main()
  File "pretraining.py", line 635, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1888, in _inner_training_loop
    self.optimizer.step()
  File "/usr/local/lib/python3.8/dist-packages/accelerate/optimizer.py", line 133, in step
    self.scaler.step(self.optimizer, closure)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/amp/grad_scaler.py", line 339, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
  0%|                                                                                                                                                                    | 0/57 [00:01<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2116) of binary: /usr/bin/python3
```

**Comment by QJBX-DJN** [comment]
使用CUDA_VISIBLE_DEVICES=0,1 python pretraining.py ...也出现相同的问题

**Comment by shibing624** [comment]
requirement.txt 的库升级到最新版本。

**Comment by QJBX-DJN** [comment]
> requirements.txt 的库升级到最新版本。
这是当前使用库的版本：
loguru=0.70
transformers=4.31.0
sentencepiece=0.1.9
datasets=2.14.0
tensorboard=2.11.2
tqdm=4.64.1
peft=0.4.0
accelerate=0.21.0
trl=0.4.7

**Comment by QJBX-DJN** [comment]
> > requirements.txt 的库升级到最新版本。 python版本：3.8.10 这是当前使用库的版本： loguru=0.70 变形金刚=4.31.0 句子=0.1.9 数据集=2.14.0 张量板=2.11.2 TQDM=4.64.1 PEFT=0.4.0 加速=0.21.0 TRL=0.4.7
升级到：
```
accelerate                    0.21.0                  
datasets                      2.14.2                  
loguru                        0.7.0                   
peft                          0.4.0                   
sentencepiece                 0.1.99                  
tensorboard                   2.13.0                  
tqdm                          4.65.0                  
transformers                  4.31.0                  
trl                           0.4.7  
```
依然出现该问题

**Comment by shibing624** [comment]
环境有问题，请到colab验证，https://colab.research.google.com/github/shibing624/MedicalGPT/blob/main/run_training_pipeline.ipynb  验证成功后，去本地环境对比解决。

**Comment by kkcondy** [comment]
> > > requests.txt 的库升级到最新版本。 python版本：3.8.10这是当前使用库的版本：
> > > accelerate=0.21.0 
> > > datasets=2.14.0 
> > > loguru=0.70 
> > > peft=0.4.0 
> > > Sentpiece=0.1.9 
> > > tensorboard=2.11 .2 
> > > tqdm=4.64.1
> > > 变形金刚=4.31.0 
> > > trl=0.4.7
> > > 升级到：
> 
> ```
> accelerate                    0.21.0                  
> datasets                      2.14.2                  
> loguru                        0.7.0                   
> peft                          0.4.0                   
> sentencepiece                 0.1.99                  
> tensorboard                   2.13.0                  
> tqdm                          4.65.0                  
> transformers                  4.31.0                  
> trl                           0.4.7  
> ```
> 
> 仍然出现该问题

问下这个解决了吗
