### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by GravitySaika** [shibing624/MedicalGPT#201]
下载[shibing624/ziya-llama-13b-medical-merged](https://huggingface.co/shibing624/ziya-llama-13b-medical-merged)，使用命令
python inference.py --model_type llama --base_model ./ziya-llama-13b-medical-merged
出现错误
Namespace(model_type='llama', base_model='/home/gem/yangqimin/MedicalGPT/ziya-llama-13b-medical-merged', lora_model='', tokenizer_path=None, template_name='vicuna', temperature=0.7, repetition_penalty=1.0, max_new_tokens=512, data_file=None, interactive=False, predictions_file='./predictions.jsonl', resize_emb=False, gpus='0', only_cpu=False)
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. If you see this, DO NOT PANIC! This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=True`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "./inference.py", line 228, in <module>
    main()
  File "./inference.py", line 112, in main
    tokenizer = tokenizer_class.from_pretrained(args.tokenizer_path, trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gem/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gem/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gem/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/transformers/models/llama/tokenization_llama.py", line 156, in __init__
    self.sp_model = self.get_spm_processor()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gem/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/transformers/models/llama/tokenization_llama.py", line 165, in get_spm_processor
    model = model_pb2.ModelProto.FromString(sp_model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
google.protobuf.message.DecodeError: Error parsing message

下载[shibing624/vicuna-baichuan-13b-chat](https://huggingface.co/shibing624/vicuna-baichuan-13b-chat)，使用命令
python inference.py --model_type baichuan --base_model ./vicuna-baichuan-13b-chat
出现错误
Namespace(model_type='baichuan', base_model='/home/gem/yangqimin/MedicalGPT/vicuna-baichuan-13b-chat', lora_model='', tokenizer_path=None, template_name='vicuna', temperature=0.7, repetition_penalty=1.0, max_new_tokens=512, data_file=None, interactive=False, predictions_file='./predictions.jsonl', resize_emb=False, gpus='0', only_cpu=False)
Traceback (most recent call last):
  File "/home/gem/yangqimin/MedicalGPT/inference.py", line 228, in <module>
    main()
  File "/home/gem/yangqimin/MedicalGPT/inference.py", line 112, in main
    tokenizer = tokenizer_class.from_pretrained(args.tokenizer_path, trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gem/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 714, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gem/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gem/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gem/.cache/huggingface/modules/transformers_modules/vicuna-baichuan-13b-chat/tokenization_baichuan.py", line 70, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/gem/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gem/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 

不知道哪里出错了，求帮助

**Comment by shibing624** [comment]
升级transformers， sentencepiece
