### ISSUE TITLE
dpo训练

### ISSUE THREAD

**Issue by Vincent131499** [shibing624/MedicalGPT#206]
### Describe the Question
Please provide a clear and concise description of what the question is.

使用run_dpo.sh训练，支持指定deepspeed config吗

**Comment by shibing624** [comment]
你可以试试。

**Comment by Vincent131499** [comment]
加上参数--deepspeed deepspeed_zero_stage2_config.json后，报如下信息，应该是没有适配：
Traceback (most recent call last):
  File "dpo_training.py", line 495, in <module>
    main()
  File "dpo_training.py", line 235, in main
    args = parser.parse_args_into_dataclasses()[0]
  File "/mnt/lustre02/jiangsu/aispeech/home/gfl18/remote/machine_translate/pretrained_llm/Jarvis/AwesomeGPT/venv-v1/lib/python3.8/site-packages/transformers/hf_argparser.py", line 355, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--deepspeed', 'deepspeed_zero_stage2_config.json']

**Comment by shibing624** [comment]
嗯，dpo不支持deepspeed。

**Comment by JingyuLi-code** [comment]
请问后续会支持DPO的deepspeed吗？
