### ISSUE TITLE
run baichuan2    with error :   AttributeError: 'NormHead' object has no attribute 'in_features'   

### ISSUE THREAD

**Issue by daiyizheng** [shibing624/MedicalGPT#229]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

我运行如下脚本：
python supervised_finetuning.py \
    --model_type baichuan \
    --model_name_or_path merged-pt \
    --train_file_dir ./data/finetune \
    --validation_file_dir ./data/finetune \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --do_train \
    --do_eval \
    --use_peft True \
    --fp16 \
    --max_train_samples 1000 \
    --max_eval_samples 10 \
    --num_train_epochs 1 \
    --learning_rate 2e-5 \
    --warmup_ratio 0.05 \
    --weight_decay 0.05 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 1 \
    --output_dir outputs-sft-v1 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True

报如下错误：
Traceback (most recent call last):
  File "/slurm/home/yrd/shaolab/daiyizheng/nlp/MedicalGPT/supervised_finetuning.py", line 978, in <module>
    main()
  File "/slurm/home/yrd/shaolab/daiyizheng/nlp/MedicalGPT/supervised_finetuning.py", line 865, in main
    model.lm_head = CastOutputToFloat(model.lm_head)
  File "/slurm/home/yrd/shaolab/daiyizheng/nlp/MedicalGPT/supervised_finetuning.py", line 198, in __init__
    self.in_features = ori_linear.in_features
  File "/slurm/home/yrd/shaolab/daiyizheng/.conda/envs/learning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'NormHead' object has no attribute 'in_features'

如下是baichuan2的源码：

<html>
<body>

class NormHead(nn.Module):
--
  | def __init__(self, hidden_size, vocab_size, bias=False):
  | super().__init__()
  | self.weight = nn.Parameter(torch.empty((vocab_size, hidden_size)))
  | nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  | self.first_flag = True
  |  
  | def forward(self, hidden_states):
  | if self.training:
  | norm_weight = nn.functional.normalize(self.weight)
  | self.first_flag = True
  | elif self.first_flag:
  | self.first_flag = False
  | self.weight.data = nn.functional.normalize(self.weight)
  | norm_weight = self.weight
  | else:
  | norm_weight = self.weight
  | return nn.functional.linear(hidden_states, norm_weight)

</body>
</html>

**Comment by daiyizheng** [comment]
代码更新已经解决， issue 关闭
