### ISSUE TITLE
使用Baichuan2-7B-Chat-4bits SFT 报错 "bitsandbytes>=0.37.0"

### ISSUE THREAD

**Issue by dage0127** [shibing624/MedicalGPT#232]
### Describe the bug
使用Baichuan2-7B-Chat-4bits SFT 报错 "bitsandbytes>=0.37.0"，分别安装了bitsandbytes 0.37.0,0.38.0,0.39.0,0.40.0,0.41.0，没有解决，详细请参考下面描述。请帮忙看看问题出在哪里。谢谢！

1.使用模型：
Baichuan2-7B-Chat-4bits
2. 使用指令：
   CUDA_VISIBLE_DEVICES=0,1 python supervised_finetuning.py     --model_type baichuan     --model_name_or_path  /home/tmp/model/Baichuan2-7B-Chat-4bits    --train_file_dir ./data/finetune     --validation_file_dir ./data/finetune     --per_device_train_batch_size 1     --per_device_eval_batch_size 1     --do_train     --do_eval     --use_peft True     --fp16     --max_train_samples 1000     --max_eval_samples 10     --num_train_epochs 1     --learning_rate 2e-5     --warmup_ratio 0.05     --weight_decay 0.05     --logging_strategy steps     --logging_steps 10     --eval_steps 50     --evaluation_strategy steps     --save_steps 500     --save_strategy steps     --save_total_limit 3     --gradient_accumulation_steps 1     --preprocessing_num_workers 4     --output_dir outputs-sft-bc-v1     --overwrite_output_dir     --ddp_timeout 30000     --logging_first_step True     --target_modules all     --lora_rank 8     --lora_alpha 16     --lora_dropout 0.05     --torch_dtype float16     --device_map auto     --report_to tensorboard     --ddp_find_unused_parameters False     --gradient_checkpointing True     --cache_dir ./cache
4. 错误：
 2023-10-19 16:19:32.321 | INFO     | __main__:main:869 - Fine-tuning method: LoRA(PEFT)
2023-10-19 16:19:32.322 | INFO     | __main__:main:880 - Peft target_modules: ['W_pack', 'down_proj', 'gate_proj', 'o_proj', 'up_proj']
2023-10-19 16:19:32.322 | INFO     | __main__:main:881 - Peft lora_rank: 8
trainable params: 17,891,328 || all params: 7,523,864,576 || trainable%: 0.23779439168895536
Traceback (most recent call last):
  File "supervised_finetuning.py", line 977, in <module>
    main()
  File "supervised_finetuning.py", line 918, in main
    trainer = SavePeftModelTrainer(
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/transformers/trainer.py", line 414, in __init__
    raise ValueError(
ValueError: The model you want to train is loaded in 8-bit precision.  if you want to fine-tune an 8-bit model, please make sure that you have installed `bitsandbytes>=0.37.0`. 

6. 尝试操作：
  分别安装了bitsandbytes 0.37.0,0.38.0,0.39.0,0.40.0,0.41.0；
 - bitsandbytes 0.40.0,0.41.0，报如下错误：
 
  Traceback (most recent call last):
  File "supervised_finetuning.py", line 977, in <module>
    main()
  File "supervised_finetuning.py", line 918, in main
    trainer = SavePeftModelTrainer(
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/transformers/trainer.py", line 414, in __init__
    raise ValueError(
ValueError: The model you want to train is loaded in 8-bit precision.  if you want to fine-tune an 8-bit model, please make sure that you have installed `bitsandbytes>=0.37.0`. 

 - bitsandbytes 0.37.0,0.38.0,0.39.0，报如下错误：
 
 Traceback (most recent call last):
  File "supervised_finetuning.py", line 977, in <module>
    main()
  File "supervised_finetuning.py", line 850, in main
    model = model_class.from_pretrained(
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
    return model_class.from_pretrained(
  File "/home/llm/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat-4bits/modeling_baichuan.py", line 601, in from_pretrained
    raise ImportError(f"Needs import model weight init func to run quantize.") 
ImportError: Needs import model weight init func to run quantize.

**Comment by shibing624** [comment]
SFT 用Baichuan2-7B-Chat，不能用-4bits的

**Comment by dage0127** [comment]
使用Baichuan2-7B-Chat可以启动，目前显卡配置是16GB*2。但训练到5%的时候，显示显存不够，失败了。

请问一下，要完成Baichuan2-7B-Chat大概需要配置多少显存？

**Comment by shibing624** [comment]
24G可以。  Baichuan-7B-Chat 可以试试，就是百川1

**Comment by dage0127** [comment]
多谢！
