### ISSUE TITLE
用bloom没问题，但是切换ChatGLM2后抛了这个异常

### ISSUE THREAD

**Issue by yuwangnexusera** [shibing624/MedicalGPT#307]
Traceback (most recent call last):
  File "/content/MedicalGPT/supervised_finetuning.py", line 1394, in <module>
    main()
  File "/content/MedicalGPT/supervised_finetuning.py", line 1315, in main
    model.gradient_checkpointing_enable()
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 1872, in gradient_checkpointing_enable
    self._set_gradient_checkpointing(enable=True, gradient_checkpointing_func=gradient_checkpointing_func)
TypeError: ChatGLMPreTrainedModel._set_gradient_checkpointing() got an unexpected keyword argument 'enable'

**Comment by shibing624** [comment]
glm模型不支持model.gradient_checkpointing_enable()，可以注释掉该行代码，或者更新代码。
