### ISSUE TITLE
dpo训练出错

### ISSUE THREAD

**Issue by cove1011** [shibing624/MedicalGPT#342]
File "F:\xiazai\MedicalGPT-main\dpo_training.py", line 497, in <module>
    main()
  File "F:\xiazai\MedicalGPT-main\dpo_training.py", line 472, in main
    train_result = trainer.train()
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\transformers\trainer.py", line 1624, in train
    return inner_training_loop(
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\transformers\trainer.py", line 1928, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\accelerate\data_loader.py", line 452, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\trl\trainer\utils.py", line 332, in __call__
    to_pad = [torch.LongTensor(ex[k]) for ex in features]
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\trl\trainer\utils.py", line 332, in <listcomp>
    to_pad = [torch.LongTensor(ex[k]) for ex in features]
TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by cove1011** [comment]
C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
trainable params: 14823424 || all params: 6258407424 || trainable%: 0.23685616796302714
  0%|          | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "F:\xiazai\MedicalGPT-main\dpo_training.py", line 497, in <module>
    main()
  File "F:\xiazai\MedicalGPT-main\dpo_training.py", line 472, in main
    train_result = trainer.train()
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\transformers\trainer.py", line 1624, in train
    return inner_training_loop(
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\transformers\trainer.py", line 1928, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\accelerate\data_loader.py", line 452, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\trl\trainer\utils.py", line 332, in __call__
    to_pad = [torch.LongTensor(ex[k]) for ex in features]
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\trl\trainer\utils.py", line 332, in <listcomp>
    to_pad = [torch.LongTensor(ex[k]) for ex in features]
TypeError: 'NoneType' object cannot be interpreted as an integer
  0%|          | 0/100 [00:00<?, ?it/s]

**Comment by shibing624** [comment]
自行在colab测试，注意库的版本。

**Comment by cove1011** [comment]
没有用啊哥

**Comment by badmic** [comment]
@shibing624 @cove1011 我也是这个问题，请问解决了吗

**Comment by huyidu** [comment]
我也是这个问题，大家解决没？
