### ISSUE TITLE
ValueError: The model does not have a language model head, please use a model that has one.

### ISSUE THREAD

**Issue by cove1011** [shibing624/MedicalGPT#345]
Traceback (most recent call last):
  File "F:\xiazai\MedicalGPT-main\ppo_training.py", line 516, in <module>
    main()
  File "F:\xiazai\MedicalGPT-main\ppo_training.py", line 270, in main
    model = AutoModelForCausalLMWithValueHead.from_pretrained(
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\trl\models\modeling_base.py", line 276, in from_pretrained
    model = cls(pretrained_model, **multi_adapter_args, **trl_model_args)
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\trl\models\modeling_value_head.py", line 112, in __init__
    raise ValueError("The model does not have a language model head, please use a model that has one.")
ValueError: The model does not have a language model head, please use a model that has one.

**Comment by shibing624** [comment]
https://github.com/shibing624/MedicalGPT/wiki/FAQ
