### ISSUE TITLE
使用qwen进行pretrain的时候出现了问题：Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by cove1011** [shibing624/MedicalGPT#346]
Traceback (most recent call last):
  File "F:\xiazai\MedicalGPT-main\pretraining.py", line 781, in <module>
    main()
  File "F:\xiazai\MedicalGPT-main\pretraining.py", line 722, in main
    trainer = SavePeftModelTrainer(
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\transformers\trainer.py", line 489, in __init__
    self._move_model_to_device(model, args.device)
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\transformers\trainer.py", line 730, in _move_model_to_device
    model = model.to(device)
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\torch\nn\modules\module.py", line 1152, in to
    return self._apply(convert)
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
    module._apply(fn)
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
    module._apply(fn)
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\torch\nn\modules\module.py", line 825, in _apply
    param_applied = fn(param)
  File "C:\Users\admin\.conda\envs\newrlhf\lib\site-packages\torch\nn\modules\module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

**Comment by shibing624** [comment]
显存不够，量化模型或者换机器。
