### ISSUE TITLE
复现医疗大模型与训练数据加载问题

### ISSUE THREAD

**Issue by veresse** [shibing624/MedicalGPT#425]
### Describe the Question
Please provide a clear and concise description of what the question is.

我在复现过程中，预训练阶段数据集在加载过程的中，出现这个报错：Running tokenizer on dataset (num_proc=10): 100%|████████████████████████████████████████████████████████▉| 1368806/1370895 [29:46<01:07, 30.89 examples/s][rank3]:[W1001 13:40:02.778279096 socket.cpp:428] [c10d] While waitForInput, poolFD failed with (errno: 0 - Success).
[rank1]:[W1001 13:40:02.817983009 socket.cpp:428] [c10d] While waitForInput, poolFD failed with (errno: 0 - Success).
[rank3]: Traceback (most recent call last):
[rank3]:   File "/data/ctr/MedicalGPT/pretraining.py", line 779, in <module>
[rank3]:     main()
[rank3]:   File "/data/ctr/MedicalGPT/pretraining.py", line 541, in main
[rank3]:     with training_args.main_process_first(desc="Dataset tokenization and grouping"):
[rank3]:   File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/contextlib.py", line 137, in __enter__
[rank3]:     return next(self.gen)
[rank3]:            ^^^^^^^^^^^^^^
[rank3]:   File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/transformers/training_args.py", line 2410, in main_process_first
[rank3]:     dist.barrier()
[rank3]:   File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank3]:     return func(*args, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3936, in barrier
[rank3]:     work = default_pg.barrier(opts=opts)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]: torch.distributed.DistBackendError: [3] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout
[rank3]: Exception raised from doWait at ../torch/csrc/distributed/c10d/TCPStore.cpp:570 (most recent call first):
[rank3]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f34bbb77f86 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libc10.so)
[rank3]: frame #1: <unknown function> + 0x164b9c5 (0x7f34a32309c5 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #2: c10d::TCPStore::doGet(std::string const&) + 0x32 (0x7f34a78e0d92 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #3: c10d::TCPStore::get(std::string const&) + 0xa1 (0x7f34a78e1f81 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #4: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7f34a78969d1 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7f34a78969d1 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7f34a78969d1 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7f34a78969d1 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #8: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x7f346db8d91f in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank3]: frame #9: c10d::ProcessGroupNCCL::getNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x114c (0x7f346db996fc in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank3]: frame #10: <unknown function> + 0x11dbb5f (0x7f346dba1b5f in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank3]: frame #11: c10d::ProcessGroupNCCL::allreduce_impl(at::Tensor&, c10d::AllreduceOptions const&) + 0x10 (0x7f346dba2f90 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank3]: frame #12: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x69c (0x7f346dbb009c in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank3]: frame #13: <unknown function> + 0x5ca4202 (0x7f34a7889202 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #14: <unknown function> + 0x5caea05 (0x7f34a7893a05 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #15: <unknown function> + 0x52d0c1b (0x7f34a6eb5c1b in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #16: <unknown function> + 0x52ce494 (0x7f34a6eb3494 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #17: <unknown function> + 0x1ace5a8 (0x7f34a36b35a8 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #18: <unknown function> + 0x5cb8974 (0x7f34a789d974 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #19: <unknown function> + 0x5cb9705 (0x7f34a789e705 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank3]: frame #20: <unknown function> + 0xdbc1a8 (0x7f34bab881a8 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
[rank3]: frame #21: <unknown function> + 0x4b2534 (0x7f34ba27e534 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
[rank3]: frame #22: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x528767]
[rank3]: frame #23: _PyObject_MakeTpCall + 0x26c (0x5041ac in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank3]: frame #24: _PyEval_EvalFrameDefault + 0x6a7 (0x5116e7 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank3]: frame #25: _PyFunction_Vectorcall + 0x173 (0x538cc3 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank3]: frame #26: _PyEval_EvalFrameDefault + 0x47a9 (0x5157e9 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank3]: frame #27: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5a2c87]
[rank3]: frame #28: _PyEval_EvalFrameDefault + 0x146a (0x5124aa in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank3]: frame #29: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x557caf]
[rank3]: frame #30: _PyEval_EvalFrameDefault + 0x4b32 (0x515b72 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank3]: frame #31: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5cbeda]
[rank3]: frame #32: PyEval_EvalCode + 0x9f (0x5cb5af in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank3]: frame #33: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5ec6a7]
[rank3]: frame #34: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5e8240]
[rank3]: frame #35: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5fd192]
[rank3]: frame #36: _PyRun_SimpleFileObject + 0x19f (0x5fc55f in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank3]: frame #37: _PyRun_AnyFileObject + 0x43 (0x5fc283 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank3]: frame #38: Py_RunMain + 0x2ee (0x5f6efe in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank3]: frame #39: Py_BytesMain + 0x39 (0x5bbc79 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank3]: frame #40: <unknown function> + 0x29d90 (0x7f34c0639d90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank3]: frame #41: __libc_start_main + 0x80 (0x7f34c0639e40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank3]: frame #42: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5bbac3]
[rank3]: . This may indicate a possible application crash on rank 0 or a network set up issue.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/data/ctr/MedicalGPT/pretraining.py", line 779, in <module>
[rank1]:     main()
[rank1]:   File "/data/ctr/MedicalGPT/pretraining.py", line 541, in main
[rank1]:     with training_args.main_process_first(desc="Dataset tokenization and grouping"):
[rank1]:   File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/contextlib.py", line 137, in __enter__
[rank1]:     return next(self.gen)
[rank1]:            ^^^^^^^^^^^^^^
[rank1]:   File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/transformers/training_args.py", line 2410, in main_process_first
[rank1]:     dist.barrier()
[rank1]:   File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3936, in barrier
[rank1]:     work = default_pg.barrier(opts=opts)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: torch.distributed.DistBackendError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout
[rank1]: Exception raised from doWait at ../torch/csrc/distributed/c10d/TCPStore.cpp:570 (most recent call first):
[rank1]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f703b177f86 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libc10.so)
[rank1]: frame #1: <unknown function> + 0x164b9c5 (0x7f70228309c5 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #2: c10d::TCPStore::doGet(std::string const&) + 0x32 (0x7f7026ee0d92 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #3: c10d::TCPStore::get(std::string const&) + 0xa1 (0x7f7026ee1f81 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #4: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7f7026e969d1 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7f7026e969d1 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7f7026e969d1 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7f7026e969d1 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #8: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x7f6fed18d91f in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank1]: frame #9: c10d::ProcessGroupNCCL::getNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x114c (0x7f6fed1996fc in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank1]: frame #10: <unknown function> + 0x11dbb5f (0x7f6fed1a1b5f in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank1]: frame #11: c10d::ProcessGroupNCCL::allreduce_impl(at::Tensor&, c10d::AllreduceOptions const&) + 0x10 (0x7f6fed1a2f90 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank1]: frame #12: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x69c (0x7f6fed1b009c in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank1]: frame #13: <unknown function> + 0x5ca4202 (0x7f7026e89202 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #14: <unknown function> + 0x5caea05 (0x7f7026e93a05 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #15: <unknown function> + 0x52d0c1b (0x7f70264b5c1b in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #16: <unknown function> + 0x52ce494 (0x7f70264b3494 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #17: <unknown function> + 0x1ace5a8 (0x7f7022cb35a8 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #18: <unknown function> + 0x5cb8974 (0x7f7026e9d974 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #19: <unknown function> + 0x5cb9705 (0x7f7026e9e705 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank1]: frame #20: <unknown function> + 0xdbc1a8 (0x7f703a1881a8 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
[rank1]: frame #21: <unknown function> + 0x4b2534 (0x7f703987e534 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
[rank1]: frame #22: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x528767]
[rank1]: frame #23: _PyObject_MakeTpCall + 0x26c (0x5041ac in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank1]: frame #24: _PyEval_EvalFrameDefault + 0x6a7 (0x5116e7 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank1]: frame #25: _PyFunction_Vectorcall + 0x173 (0x538cc3 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank1]: frame #26: _PyEval_EvalFrameDefault + 0x47a9 (0x5157e9 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank1]: frame #27: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5a2c87]
[rank1]: frame #28: _PyEval_EvalFrameDefault + 0x146a (0x5124aa in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank1]: frame #29: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x557caf]
[rank1]: frame #30: _PyEval_EvalFrameDefault + 0x4b32 (0x515b72 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank1]: frame #31: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5cbeda]
[rank1]: frame #32: PyEval_EvalCode + 0x9f (0x5cb5af in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank1]: frame #33: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5ec6a7]
[rank1]: frame #34: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5e8240]
[rank1]: frame #35: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5fd192]
[rank1]: frame #36: _PyRun_SimpleFileObject + 0x19f (0x5fc55f in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank1]: frame #37: _PyRun_AnyFileObject + 0x43 (0x5fc283 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank1]: frame #38: Py_RunMain + 0x2ee (0x5f6efe in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank1]: frame #39: Py_BytesMain + 0x39 (0x5bbc79 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank1]: frame #40: <unknown function> + 0x29d90 (0x7f703fcc8d90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank1]: frame #41: __libc_start_main + 0x80 (0x7f703fcc8e40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank1]: frame #42: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5bbac3]
[rank1]: . This may indicate a possible application crash on rank 0 or a network set up issue.
[rank2]:[W1001 13:40:02.868119162 socket.cpp:428] [c10d] While waitForInput, poolFD failed with (errno: 0 - Success).
[rank2]: Traceback (most recent call last):
[rank2]:   File "/data/ctr/MedicalGPT/pretraining.py", line 779, in <module>
[rank2]:     main()
[rank2]:   File "/data/ctr/MedicalGPT/pretraining.py", line 541, in main
[rank2]:     with training_args.main_process_first(desc="Dataset tokenization and grouping"):
[rank2]:   File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/contextlib.py", line 137, in __enter__
[rank2]:     return next(self.gen)
[rank2]:            ^^^^^^^^^^^^^^
[rank2]:   File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/transformers/training_args.py", line 2410, in main_process_first
[rank2]:     dist.barrier()
[rank2]:   File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank2]:     return func(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3936, in barrier
[rank2]:     work = default_pg.barrier(opts=opts)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: torch.distributed.DistBackendError: [2] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout
[rank2]: Exception raised from doWait at ../torch/csrc/distributed/c10d/TCPStore.cpp:570 (most recent call first):
[rank2]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fdec5e9af86 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libc10.so)
[rank2]: frame #1: <unknown function> + 0x164b9c5 (0x7fdead6309c5 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #2: c10d::TCPStore::doGet(std::string const&) + 0x32 (0x7fdeb1ce0d92 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #3: c10d::TCPStore::get(std::string const&) + 0xa1 (0x7fdeb1ce1f81 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #4: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fdeb1c969d1 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fdeb1c969d1 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fdeb1c969d1 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x7fdeb1c969d1 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #8: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x7fde77f8d91f in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank2]: frame #9: c10d::ProcessGroupNCCL::getNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x114c (0x7fde77f996fc in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank2]: frame #10: <unknown function> + 0x11dbb5f (0x7fde77fa1b5f in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank2]: frame #11: c10d::ProcessGroupNCCL::allreduce_impl(at::Tensor&, c10d::AllreduceOptions const&) + 0x10 (0x7fde77fa2f90 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank2]: frame #12: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0x69c (0x7fde77fb009c in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
[rank2]: frame #13: <unknown function> + 0x5ca4202 (0x7fdeb1c89202 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #14: <unknown function> + 0x5caea05 (0x7fdeb1c93a05 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #15: <unknown function> + 0x52d0c1b (0x7fdeb12b5c1b in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #16: <unknown function> + 0x52ce494 (0x7fdeb12b3494 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #17: <unknown function> + 0x1ace5a8 (0x7fdeadab35a8 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #18: <unknown function> + 0x5cb8974 (0x7fdeb1c9d974 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #19: <unknown function> + 0x5cb9705 (0x7fdeb1c9e705 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
[rank2]: frame #20: <unknown function> + 0xdbc1a8 (0x7fdec4f881a8 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
[rank2]: frame #21: <unknown function> + 0x4b2534 (0x7fdec467e534 in /home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
[rank2]: frame #22: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x528767]
[rank2]: frame #23: _PyObject_MakeTpCall + 0x26c (0x5041ac in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank2]: frame #24: _PyEval_EvalFrameDefault + 0x6a7 (0x5116e7 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank2]: frame #25: _PyFunction_Vectorcall + 0x173 (0x538cc3 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank2]: frame #26: _PyEval_EvalFrameDefault + 0x47a9 (0x5157e9 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank2]: frame #27: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5a2c87]
[rank2]: frame #28: _PyEval_EvalFrameDefault + 0x146a (0x5124aa in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank2]: frame #29: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x557caf]
[rank2]: frame #30: _PyEval_EvalFrameDefault + 0x4b32 (0x515b72 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank2]: frame #31: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5cbeda]
[rank2]: frame #32: PyEval_EvalCode + 0x9f (0x5cb5af in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank2]: frame #33: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5ec6a7]
[rank2]: frame #34: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5e8240]
[rank2]: frame #35: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5fd192]
[rank2]: frame #36: _PyRun_SimpleFileObject + 0x19f (0x5fc55f in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank2]: frame #37: _PyRun_AnyFileObject + 0x43 (0x5fc283 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank2]: frame #38: Py_RunMain + 0x2ee (0x5f6efe in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank2]: frame #39: Py_BytesMain + 0x39 (0x5bbc79 in /home/server/anaconda3/envs/medicalgpt/bin/python)
[rank2]: frame #40: <unknown function> + 0x29d90 (0x7fdeca916d90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank2]: frame #41: __libc_start_main + 0x80 (0x7fdeca916e40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank2]: frame #42: /home/server/anaconda3/envs/medicalgpt/bin/python() [0x5bbac3]
[rank2]: . This may indicate a possible application crash on rank 0 or a network set up issue.
W1001 13:40:03.742000 140703168014144 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 457151 closing signal SIGTERM
W1001 13:40:03.745000 140703168014144 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 457152 closing signal SIGTERM
W1001 13:40:03.745000 140703168014144 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 457153 closing signal SIGTERM
E1001 13:40:03.910000 140703168014144 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 3 (pid: 457154) of binary: /home/server/anaconda3/envs/medicalgpt/bin/python
Traceback (most recent call last):
  File "/home/server/anaconda3/envs/medicalgpt/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/server/anaconda3/envs/medicalgpt/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
pretraining.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-01_13:40:03
  host      : gpu-server
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 457154)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
我使用的是提供的医疗数据集和通用数据集，加起来有130w行，其中通用数据集有100w行，使用了4*4090显卡，请大佬们帮忙看看为什么会出错。

**Comment by veresse** [comment]
解决这个问题了，原因是多卡在加载数据的时候网络可能会出错，可以修改cache文件使用单卡先加载，然后再切换为多卡运行
