### ISSUE TITLE
lora模型权重合并到chatglm2-6b

### ISSUE THREAD

**Issue by richard880502** [shibing624/MedicalGPT#44]
在運行合併權重這個步驟時會出現以下的錯誤

Traceback (most recent call last):
  File "merge_peft_adapter.py", line 100, in <module>
    main()
  File "merge_peft_adapter.py", line 80, in main
    base_model.resize_token_embeddings(len(tokenizer))
  File "/home/largitdata/miniconda3/envs/chatglm/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1395, in resize_token_embeddings
    model_embeds = self._resize_token_embeddings(new_num_tokens)
  File "/home/largitdata/miniconda3/envs/chatglm/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1411, in _resize_token_embeddings
    self.set_input_embeddings(new_embeddings)
  File "/home/largitdata/miniconda3/envs/chatglm/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1236, in set_input_embeddings
    base_model.set_input_embeddings(value)
  File "/home/largitdata/miniconda3/envs/chatglm/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1238, in set_input_embeddings
    raise NotImplementedError
NotImplementedError

想了解有誰知道這個問題要怎麼解決嗎～謝謝

**Comment by shibing624** [comment]
如果没有扩词表，注释80行。

**Comment by richard880502** [comment]
感謝回覆,註解後一切正常謝謝！
