### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper__index_select)

### ISSUE THREAD

**Issue by dage0127** [shibing624/MedicalGPT#52]
运行脚本： python gradio_demo.py --base_model IDEA-CCNL/Ziya-LLaMA-13B-v1  --model_type llama
或者运行脚本：python gradio_demo.py --base_model IDEA-CCNL/Ziya-LLaMA-13B-v1  --gpus 0,1 --model_type llama
都报如下错误：

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper__index_select)

日志：

(gpt) llm@ht-PowerEdge-R740:/home/haitaiwork/gen/mediacal$ python gradio_demo.py --base_model IDEA-CCNL/Ziya-LLaMA-13B-v1  --model_type llama

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/haitaiwork/llm/anaconda3/envs/gpt did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/openmpi/lib')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/lib/x86_64-linux-gnu/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 111
CUDA SETUP: Loading binary /home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111.so...
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:28<00:00,  1.03s/it]
/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/gradio/components/textbox.py:259: UserWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  warnings.warn(
Running on local URL:  http://0.0.0.0:8081

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "gradio_demo.py", line 156, in predict
    generation_output = model.generate(
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/transformers/generation/utils.py", line 1611, in generate
    return self.beam_search(
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/transformers/generation/utils.py", line 2982, in beam_search
    model_kwargs["past_key_values"] = self._reorder_cache(model_kwargs["past_key_values"], beam_idx)
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 762, in _reorder_cache
    reordered_past += (tuple(past_state.index_select(0, beam_idx) for past_state in layer_past),)
  File "/home/haitaiwork/llm/anaconda3/envs/gpt/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 762, in <genexpr>
    reordered_past += (tuple(past_state.index_select(0, beam_idx) for past_state in layer_past),)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper__index_select)

**Comment by shibing624** [comment]
cc https://github.com/shibing624/MedicalGPT/issues/34
