### ISSUE TITLE
恢复预训练时报OOM.

### ISSUE THREAD

**Issue by Halflifefa** [shibing624/MedicalGPT#57]
### Describe the Question
Please provide a clear and concise description of what the question is.
预训练运行的过程中意外停止了,执行恢复预训练后报了OOM错误,但是其他参数设置都没变,如下:
CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node 1 pretraining.py \
    --model_type llama \
    --deepspeed deepspeed_config.json \
    --model_name_or_path ./model/chinese-llama-plus-7b-merged \
    --peft_path ./outputs-pt-v1/checkpoint-2500 \
    --train_file_dir ./data/pretrain \
    --validation_file_dir ./data/pretrain \
    --per_device_train_batch_size 64 \
    --per_device_eval_batch_size 64 \
    --do_train \
    --do_eval \
    --use_peft True \
    --seed 42 \
    --fp16 \
    --max_train_samples -1 \
    --max_eval_samples 10 \
    --num_train_epochs 3 \
    --learning_rate 2e-4 \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 7 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 1 \
    --block_size 1024 \
    --output_dir outputs-pt-v2 \
    # --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True

**Comment by shibing624** [comment]
是在哪里报错的，报错信息给下。

可能的原因：`model = PeftModel.from_pretrained(model, training_args.peft_path, is_trainable=True)`加载lora报错了，看你用了deepspeed，当前deepspeed好像对lora支持不稳定，可以删除`--deepspeed deepspeed_config.json`试试

**Comment by Halflifefa** [comment]
感谢回答,如下是详细报错信息
2023-07-02 22:37:48.876 | INFO     | __main__:main:622 - *** Train ***
2023-07-02 22:37:48.997 | DEBUG    | __main__:main:623 - Train dataloader example: {'input_ids': tensor([[  191,   177, 29871,  ..., 31196, 32949, 30419],
        [35353, 30409, 44395,  ..., 33150, 30214, 32010],
        [34493, 20097,   353,  ..., 45017, 32308, 33727],
        ...,
        [  152,   242,   192,  ...,   192,   151, 31936],
        [31608, 32170, 34102,  ..., 13072, 29889, 33575],
        [  146, 29871,   242,  ..., 29871, 30732, 29871]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1]]), 'labels': tensor([[  191,   177, 29871,  ..., 31196, 32949, 30419],
        [35353, 30409, 44395,  ..., 33150, 30214, 32010],
        [34493, 20097,   353,  ..., 45017, 32308, 33727],
        ...,
        [  152,   242,   192,  ...,   192,   151, 31936],
        [31608, 32170, 34102,  ..., 13072, 29889, 33575],
        [  146, 29871,   242,  ..., 29871, 30732, 29871]])}
Rank: 0 partition count [1] and sizes[(19988480, False)] 
  0%|                                                                                                                              | 0/3486 [00:00<?, ?it/s]Traceback (most recent call last):
  File "pretraining.py", line 655, in <module>
    main()
  File "pretraining.py", line 627, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 2784, in compute_loss
    outputs = model(**inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1735, in forward
    loss = self.module(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/peft/peft_model.py", line 678, in forward
    return self.base_model(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 305, in forward
    hidden_states = self.mlp(hidden_states)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 155, in forward
    return self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/peft/tuners/lora.py", line 570, in forward
    self.lora_B[self.active_adapter](
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.34 GiB (GPU 0; 79.32 GiB total capacity; 76.41 GiB already allocated; 839.56 MiB free; 77.06 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|                                                                                                                              | 0/3486 [00:01<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1114) of binary: /root/miniconda3/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
pretraining.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-02_22:37:55
  host      : autodl-container-78a811a500-b3802e39
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1114)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
bash: --ddp_timeout: command not found

此外,尝试将--deepspeed deepspeed_config.json删除也不行

**Comment by shibing624** [comment]
# --overwrite_output_dir 这行删除，shell里面不可以加# ，要么写顶部，要么删除。

**Comment by Halflifefa** [comment]
> `# --overwrite_output_dir `这行删除，shell里面不可以加# ，要么写顶部，要么删除。

发现这个问题了,低级错误,感谢解答
