### ISSUE TITLE
基于ChatGLM2运行run_pt.py报错

### ISSUE THREAD

**Issue by elijah-hz** [shibing624/MedicalGPT#65]
pip install -r requirements.txt
采用原有的数据，其他都没修改。请教大佬可能什么原因。

Traceback (most recent call last):
  File "/home/ai/workspace/medical/MedicalGPT/pretraining.py", line 655, in <module>
    main()
  File "/home/ai/workspace/medical/MedicalGPT/pretraining.py", line 601, in main
    model.enable_input_require_grads()
  File "/home/ai/anaconda3/envs/chatglm-tun/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1206, in enable_input_require_grads
    self._require_grads_hook = self.get_input_embeddings().register_forward_hook(make_inputs_require_grads)
  File "/home/ai/anaconda3/envs/chatglm-tun/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1223, in get_input_embeddings
    return base_model.get_input_embeddings()
  File "/home/ai/anaconda3/envs/chatglm-tun/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1225, in get_input_embeddings
    raise NotImplementedError
NotImplementedError
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 44506) of binary: /home/ai/anaconda3/envs/chatglm-tun/bin/python
Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/chatglm-tun/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ai/anaconda3/envs/chatglm-tun/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ai/anaconda3/envs/chatglm-tun/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/ai/anaconda3/envs/chatglm-tun/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/ai/anaconda3/envs/chatglm-tun/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ai/anaconda3/envs/chatglm-tun/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by elijah-hz** [comment]
下载[ChatGLM2-6b](https://huggingface.co/THUDM/chatglm2-6b/tree/main): 最新的modeling_chatglm.py 和 config.json 就可以正确运行了
