### ISSUE TITLE
使用deepspeed run run_rm.sh

### ISSUE THREAD

**Issue by yangzhipeng1108** [shibing624/MedicalGPT#73]
Could not estimate the number of tokens of the input, floating-point operations will not be computed
Traceback (most recent call last):
  File "/root/nas-share/chat/MedicalGPT-main/reward_modeling.py", line 643, in <module>
    main()
  File "/root/nas-share/chat/MedicalGPT-main/reward_modeling.py", line 615, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/usr/local/conda/lib/python3.9/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/usr/local/conda/lib/python3.9/site-packages/transformers/trainer.py", line 1881, in _inner_training_loop
    self.optimizer.step()
AttributeError: 'DummyOptim' object has no attribute 'step'

RewardTrainer是否支持deepspeed

**Comment by yangzhipeng1108** [comment]
请问大神，什么版本比较合适

**Comment by xxm1668** [comment]
0.9.2

**Comment by yinheng-gh** [comment]
我是在运行pretrain的时候遇到这个问题，把deepspeed改成0.9.2会在accelerate检查依赖版本时提示最低需要0.9.3，然后改成0.9.3，还是会遇到上面那个问题
