### ISSUE TITLE
RuntimeError: Distributed package doesn't have NCCL built in when pretrain

### ISSUE THREAD

**Issue by SeekPoint** [shibing624/MedicalGPT#77]
```(gh_MedicalGPT) amd00@MZ32-00:~/llm_dev/MedicalGPT$ bash run_pt.sh
Traceback (most recent call last):
  File "/home/amd00/llm_dev/MedicalGPT/pretraining.py", line 655, in <module>
    main()
  File "/home/amd00/llm_dev/MedicalGPT/pretraining.py", line 349, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/transformers/hf_argparser.py", line 346, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 118, in __init__
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/transformers/training_args.py", line 1340, in __post_init__
    and (self.device.type != "cuda")
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/transformers/training_args.py", line 1764, in device
    return self._setup_devices
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/transformers/training_args.py", line 1695, in _setup_devices
    self.distributed_state = PartialState(backend=self.ddp_backend)
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/accelerate/state.py", line 191, in __init__
    torch.distributed.init_process_group(backend=self.backend, **kwargs)
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 12387) of binary: /home/amd00/anaconda3/envs/gh_MedicalGPT/bin/python
Traceback (most recent call last):
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/bin/torchrun", line 11, in <module>
    sys.exit(main())
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/amd00/anaconda3/envs/gh_MedicalGPT/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
pretraining.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-08_18:14:34
  host      : MZ32-00
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 12387)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by shibing624** [comment]
use python train you model, not torchrun
