### ISSUE TITLE
chatglm2进行进行lora权重合并报错

### ISSUE THREAD

**Issue by lzw2000118** [shibing624/MedicalGPT#92]
显示缺少文件
Traceback (most recent call last):
  File "merge_peft_adapter.py", line 100, in <module>
    main()
  File "merge_peft_adapter.py", line 77, in main
    tokenizer = tokenizer_class.from_pretrained(peft_model_path, trust_remote_code=True)
  File "/root/anaconda3/envs/medical_venv/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 676, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/medical_venv/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 431, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/root/anaconda3/envs/medical_venv/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 247, in get_cached_module_file
    resolved_module_file = cached_file(
  File "/root/anaconda3/envs/medical_venv/lib/python3.8/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: output-chatglm2/chatglm2-pt-v1 does not appear to have a file named tokenization_chatglm.py. Checkout 'https://huggingface.co/output-chatglm2/chatglm2-pt-v1/None' for available files.

**Comment by shibing624** [comment]
see https://github.com/shibing624/MedicalGPT/issues/68

**Comment by lzw2000118** [comment]
感谢大神解答！ 不过这边把py文件复制过去之后又报了这个错误，麻烦大神看一下
Traceback (most recent call last):
  File "merge_peft_adapter.py", line 100, in <module>
    main()
  File "merge_peft_adapter.py", line 80, in main
    base_model.resize_token_embeddings(len(tokenizer))
  File "/root/anaconda3/envs/medical_venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1395, in resize_token_embeddings
    model_embeds = self._resize_token_embeddings(new_num_tokens)
  File "/root/anaconda3/envs/medical_venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1411, in _resize_token_embeddings
    self.set_input_embeddings(new_embeddings)
  File "/root/anaconda3/envs/medical_venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1236, in set_input_embeddings
    base_model.set_input_embeddings(value)
  File "/root/anaconda3/envs/medical_venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1238, in set_input_embeddings
    raise NotImplementedError
NotImplementedError

**Comment by shibing624** [comment]
注释第80行

**Comment by lzw2000118** [comment]
> 注释第80行

谢谢大神 解决了！

**Comment by Alfer-Feng** [comment]
请问需要chatglm2除了上述修改还需要修改其他吗？
