### ISSUE TITLE
ValueError: Attempting to unscale FP16 gradients.

### ISSUE THREAD

**Issue by gaoxc0315** [shibing624/MedicalGPT#94]
### Describe the bug
使用这个参数--use_peft False，会报ValueError: Attempting to unscale FP16 gradients.这个错误，这个如何解决啊，有遇到的吗？

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
  0% 0/76 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/MedicalGPT/pretraining.py", line 655, in <module>
    main()
  File "/content/MedicalGPT/pretraining.py", line 627, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1987, in _inner_training_loop
    self.accelerator.clip_grad_norm_(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1925, in clip_grad_norm_
    self.unscale_gradients()
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1888, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
  0% 0/76 [00:04<?, ?it/s]

**Comment by wusi1590** [comment]
同样的问题，请问怎么解决的？

**Comment by shibing624** [comment]
设置为fp32呀，我的wiki写了的。https://github.com/shibing624/MedicalGPT/wiki/%E8%AE%AD%E7%BB%83%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E
